name: Deploy static site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build site
        run: echo "Build your site here"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: enablement: true
          # Optionally set 'enablement: true' if needed
